version: '3'
services:
    bus-booking-db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: unless-stopped
        volumes:
            - ./db_data:/var/lib/mysql
            - ./_db:/backup
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            bus-booking:
                aliases:
                    - "bus-booking-db.localhost.com"
    bus-booking-services:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - ${SERVICE_PORT}:80
        depends_on: 
            - bus-booking-db
        links:
            - bus-booking-db
        networks:
            bus-booking:
                aliases:
                    - bus-booking.localhost.com
volumes:
    db_data:
    src:
networks:
    bus-booking: